### ISSUE TITLE
Link de download do crackme do exercício do Cabeçalho/COFF está quebrado

### ISSUE THREAD

**Issue by becauro** [mentebinaria/fundamentos-engenharia-reversa#24]
O link de download do crackme no [exercício da seção Cabeçalhos e subseção COFF](https://mentebinaria.gitbook.io/engenharia-reversa/o-formato-pe/cabecalhos/coff#exercicio) está quebrado.
Abri um Pull Request para colaborar com a correção.
O link de download correto seria [esse](https://www.mentebinaria.com.br/files/file/19-crackme-do-cruehead/).

![Link_crackme_in_exerc_cabe_coff](https://user-images.githubusercontent.com/61303294/195546418-3771e104-446f-4c39-b179-cb4aae9d06aa.png)

**Comment by merces** [comment]
Fixed by #23
