### ISSUE TITLE
Continuar sugerindo Windows 7?

### ISSUE THREAD

**Issue by hudsantos** [mentebinaria/fundamentos-engenharia-reversa#3]
Aqui na parte de preparação do ambiente: https://mentebinaria.gitbook.io/engenharia-reversa/antes-de-comecar#preparacao-do-ambiente

...De inicio achei que não fazia sentido sugerir Windows 7, e sim um Windows ou Linux qualquer desde que seja atual. Ou até mesmo programar dentro de container ao invés de uma VM completona pra isso. Entretando, mais à frente notei que tem bastante programa de Windows envolvido, o que justifica a sugestão dum SO Windows..

Mas não poderia sugerir ja o Windows 10? Ou o que precisaria pra poder sugerir o Windows 10 nesse contexto? Teriamos que testar o funcionamento de todas as ferramentas no Win10, como que homologando o funcionamento?

Note que, [ao que tudo indica](https://support.microsoft.com/pt-br/help/4057281/windows-7-support-will-end-on-january-14-2020), a Microsoft deve encerrar o suporte ao Windows 7 no dia 14 de Janeiro de 2020. Faltam praticamente 8 meses pra isso.

Valeu!

**Comment by merces** [comment]
Excelente ponto. Já atualizei e tô adaptando e testando as passagens que utilizam Windows. Obrigado!
